led.enable(false)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P7, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P6, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P5, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P4, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P3, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P7, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P6, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P5, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P4, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P3, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
})
